import = ["/Users/eric/.config/alacritty/themes/thelovelace.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 2

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Command"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = true
# gtk_theme_variant = "dark"
opacity = 0.9

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 0
y = 0
