theme = "dark_plus"

[editor]
line-number = "relative"
scrolloff = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":w"
"ret" = ["open_below", "normal_mode"]
"space" = { c = "toggle_comments" }

[keys.insert]
j = { k = "normal_mode" }