[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config]
check = { command = "clippy", features = "all" }
diagnostics = { experimental = { enable = true } }
hover = { actions = { enable = true } }
typing = { autoClosingAngleBrackets = { enable = true } }
cargo = { allFeatures = true }
procMacro = { enable = true }

# [language.auto-pairs]
# '<' = '>'


[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[[language]]
name = "python"
language-servers = ["pyrefly"]


[[language]]
name = "zig"
language-servers = ["zls"]

[language-server.zls]
# omit the following line if `zls` is in your PATH
# command = "/path/to/zls_executable"
# There are two ways to set config options:
#   - edit your `zls.json` that applies to any editor that uses ZLS
#   - set in-editor config options with the `config.<name>` fields below.
#
# Further information on how to configure ZLS:
# https://zigtools.org/zls/configure/

# omit the following line if `zig` is in your PATH
# config.zig_exe_path = "/path/to/zig_executable"
config.enable_build_on_save = true


[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true


# ------------------------------------------------ Web ------------------------------------------------ 
[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  # "emmet-language-server",
]
# formatter = { command = "biome", args = ["format", "--write"] }
# formatter = { command = 'bunx', args = [
#   "prettier",
#   "--parser",
#   "html",
#   "--plugin",
#   "prettier-plugin-tailwindcss",
# ] }
auto-format = true


[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls",
  # "emmet-language-server",
]
# formatter = { command = "biome", args = ["format", "--write"] }
# formatter = { command = 'bunx', args = [
#   "prettier",
#   "--parser",
#   "css",
#   "--plugin=prettier-plugin-tailwindcss",
# ] }
auto-format = true


# ------------------------------ Biome -----------------------------
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
  "tailwindcss-ls",
]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
  "tailwindcss-ls",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
  "tailwindcss-ls",
]

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
# formatter = { command = "biome", args = ["format", "--write"] }
